---
title: "Objective 3"
output: html_document
date: "2024-05-08"
Author: Léa Cavalli
---

# Set up environment
```{r}
# Clean environment
rm( list = ls() )

# load necessary libraries
library(tidyverse)

# Load data
setwd("~/GitHub/Calibration-Review")
clean_data <- read.csv("review_396964_20240504214514.csv")
# clean_data <- read.csv("Clean_data_review.csv")

```

# A. Purpose
```{r}
# A.1 Scientific problem being solved (what is the purpose of calibration?) 
score_A.1 <- clean_data |> 
  mutate(Scientific.problem.being.solved = ifelse(Scientific.problem.being.solved=="Not reported", 0, 1))|> 
  select(Scientific.problem.being.solved) 

```

# B. Inputs 
# B.1. Parameter inputs
```{r}
# B.1.1. Beliefs or evidence
score_B.1.1 <- clean_data |> 
  mutate(External.beliefs.or.evidence = ifelse(External.beliefs.or.evidence=="Not reported", 0, 1))|> 
  select(External.beliefs.or.evidence) 

# B.1.2. Choice of parameters to calibrate
score_B.1.2 <- clean_data |> 
  mutate(Choice.of.parameters.to.calibrate = ifelse(Choice.of.parameters.to.calibrate=="Not reported", 0, 1))|> 
  select(Choice.of.parameters.to.calibrate) 

# B.1.3. What justification was provided for choice of parameters to calibrate? Only for studies which calibrated a subset of parameters.
score_B.1.3 <- clean_data |> 
  mutate(What.justification.was.provided.for.choice.of.parameters.to.calibrate. = ifelse(What.justification.was.provided.for.choice.of.parameters.to.calibrate.=="Not reported ", 0, 1))|> 
  select(What.justification.was.provided.for.choice.of.parameters.to.calibrate.) 
```



# B.2. Calibration targets
```{r}
# B.2.1. Type of data used for defining calibration targets
score_B.2.1 <- clean_data |> 
  mutate(Type.of.data.used.for.defining.calibration.targets..select.all.that.apply. = ifelse(Type.of.data.used.for.defining.calibration.targets..select.all.that.apply.=="Not reported ", 0, 1))|> 
  select(Type.of.data.used.for.defining.calibration.targets..select.all.that.apply.) 

# B.2.2. Resolution of data used for defining calibration targets
score_B.2.2 <- clean_data |> 
  mutate(Resolution.of.data..used.for.defining.calibration.targets = ifelse(Resolution.of.data..used.for.defining.calibration.targets=="Not reported ", 0, 1))|> 
  select(Resolution.of.data..used.for.defining.calibration.targets) 

#  B.2.3.  How many calibration targets were used for estimation?
score_B.2.3 <- clean_data |> 
  mutate(How.many.calibration.targets.were.used.for.estimation. = ifelse(How.many.calibration.targets.were.used.for.estimation.=="Not reported ", 0, 1))|> 
  select(How.many.calibration.targets.were.used.for.estimation.) 
```


# C. Process
```{r}
# C.1. Number of steps 
score_C.1 <- clean_data |> 
  mutate(Number.of.steps..single.or.sequential. = ifelse(Number.of.steps..single.or.sequential.=="Not reported", 0, 1))|> 
  select(Number.of.steps..single.or.sequential.) 

# C.2. Name of calibration algorithm 
score_C.2 <- clean_data |> 
  mutate(Name.of.calibration.algorithm = ifelse(Name.of.calibration.algorithm=="Not reported", 0, 1))|> 
  select(Name.of.calibration.algorithm) 

# C.3. Is calibration implementation (code) available in an open-access repository? 
score_C.3 <- clean_data |> 
  mutate(Is.calibration.implementation..code..available.in.an.open.access.repository. = ifelse(Is.calibration.implementation..code..available.in.an.open.access.repository.=="Link reported and accessible", 0, 1))|> 
  select(Is.calibration.implementation..code..available.in.an.open.access.repository.) 

# C.4. Goodness-of-fit (GOF) measure employed within calibration algorithm
score_C.4 <- clean_data |> 
  mutate(Goodness.of.fit..GOF..measure.employed.within.calibration.algorithm = ifelse(Goodness.of.fit..GOF..measure.employed.within.calibration.algorithm=="Not reported", 0, 1))|> 
  select(Goodness.of.fit..GOF..measure.employed.within.calibration.algorithm) 

```

# D. Output 
```{r}
# D.1. Nature of calibration results
score_D.1 <- clean_data |> 
  mutate(Nature.of.calibration.results = ifelse(Nature.of.calibration.results=="Not reported ", 0, 1))|> 
  select(Nature.of.calibration.results) 

# D.2. How are calibration results reported? 
score_D.2 <- clean_data |> 
  mutate(How.are.calibration.results.reported. = ifelse(How.are.calibration.results.reported.=="Calibration results are not reported. ", 0, 1))|> 
  select(How.are.calibration.results.reported.) 

# D.3. How is uncertainty in calibration outputs reported? 
score_D.3 <- clean_data |> 
  mutate(How.is.uncertainty.in.calibration.outputs.reported. = ifelse(How.is.uncertainty.in.calibration.outputs.reported.=="Uncertainty in calibration outputs is not reported.", 0, 1))|> 
  select(How.is.uncertainty.in.calibration.outputs.reported.) 

# D.4. What is the size of the calibration output? 
score_D.4 <- clean_data |> 
  mutate(What.is.the.size.of.the.calibration.output. = ifelse(What.is.the.size.of.the.calibration.output.=="Not reported", 0, 1)) |> 
  select(What.is.the.size.of.the.calibration.output.) 
```



# Create table 
```{r}
Objective3_df <- cbind("Study.ID" = clean_data$Study.ID, 
      "Title" = clean_data$Title, 
      "DOI" = clean_data$Study.DOI, 
      score_A.1, 
      score_B.1.1, score_B.1.2, score_B.1.3, 
      score_B.2.1, score_B.2.2, score_B.2.3, 
      score_C.1, score_C.2, score_C.3, score_C.4, 
      score_D.1, score_D.2, score_D.3, score_D.4)

Objective3_df
```

# Add reporting comprehensiveness by article
```{r}
Objective3_df <- Objective3_df |> 
  mutate(Sum_Reporting_Score = rowSums(Objective3_df[,-(1:3)])) |> 
  mutate(Reporting_comprehensiveness = ifelse(Sum_Reporting_Score> 10, "High", 
                                                ifelse(Sum_Reporting_Score> 5, "Fair", "Low")))

Objective3_df

table(Objective3_df$Reporting_comprehensiveness)
```


# Summarise reporting score by Category
```{r}
# Number articles reporting each category
colSums(Objective3_df[,-(1:3)]) 

# Percentage articles reporting each category
round(100 * colSums(Objective3_df[,-(1:3)]) / nrow(Objective3_df))

```

