---
title: "Objective 1 - Figures"
output: html_document
date: "2024-06-25"
---

# Set up environment
```{r}
# Clean environment
rm( list = ls() )

# load necessary libraries
library(tidyverse)
library(dplyr)

# Load data
setwd("~/GitHub/Calibration-Review/1.Data Cleaning")
clean_data <- read.csv("Clean_data.csv")

# Calibration_size_range
Calibration_size_range <- clean_data |>
  separate_rows(What.is.the.size.of.the.calibration.output., Name.of.calibration.algorithm, sep = "; ")|> 
  mutate(size.of.the.calibration.output.reported = ifelse(What.is.the.size.of.the.calibration.output. == "Not reported", "Not reported", "[Number provided]"))|>
  filter(size.of.the.calibration.output.reported != "Not reported") |> 
  mutate(What.is.the.size.of.the.calibration.output.V2= as.numeric(What.is.the.size.of.the.calibration.output.))|> 
  filter( ! is.na(What.is.the.size.of.the.calibration.output.V2))

# Ask Emmanuelle 
Calibration_size_range |> 
  filter( is.na(What.is.the.size.of.the.calibration.output.V2))|>
  select(What.is.the.size.of.the.calibration.output.)

```
# Calibration size Distribution
```{r}
## Histogram - Name.of.calibration.algorithm 
subset <- Calibration_size_range|>
  filter(Name.of.calibration.algorithm != "Other ")|> 
  filter(Name.of.calibration.algorithm != "Not reported") |>
  group_by(Name.of.calibration.algorithm)|>
  summarise(algorithm_N= n())|>
  filter(algorithm_N>1) |>
  arrange(-algorithm_N)|> 
  pull(Name.of.calibration.algorithm) 

Calibration_size_range |>
  filter(Name.of.calibration.algorithm %in% subset)|>
  mutate(Name.of.calibration.algorithm = factor(Name.of.calibration.algorithm, levels=subset))|> 
  mutate(Nature.of.calibration.results = ifelse(grepl("Point", Nature.of.calibration.results), "Point estimate", 
                                                ifelse(grepl("Sample", Nature.of.calibration.results), "Sample estimate", 
                                                       ifelse(grepl("Distribution", Nature.of.calibration.results), "Distribution estimate", Nature.of.calibration.results))))|> 
  mutate(Nature.of.calibration.results = factor(Nature.of.calibration.results, levels = c("Point estimate", "Sample estimate", "Distribution estimate", "Not reported ")))|> 
  ggplot() +
  geom_histogram(aes(x=What.is.the.size.of.the.calibration.output.V2, fill=Nature.of.calibration.results))+
  scale_x_log10(breaks= c(1, 10, 100, 1000, 10000, 100000, 500000)) + 
  theme_bw()+
  facet_grid(Name.of.calibration.algorithm ~ ., scales = "free",labeller=label_wrap_gen(width=.1))+
  xlab("Size of calibration output")+
  labs(fill = "Nature of calibration results") 

## Histogram - Name.of.calibration.algorithm 
Calibration_size_range |>
  filter(! is.na(Aim.of.calibration.procedure))|> 
  filter(Aim.of.calibration.procedure != "Not reported")|> 
  mutate(Nature.of.calibration.results = ifelse(grepl("Point", Nature.of.calibration.results), "Point estimate", 
                                                ifelse(grepl("Sample", Nature.of.calibration.results), "Sample estimate", 
                                                       ifelse(grepl("Distribution", Nature.of.calibration.results), "Distribution estimate", Nature.of.calibration.results))))|> 
  mutate(Nature.of.calibration.results = factor(Nature.of.calibration.results, levels = c("Point estimate", "Sample estimate", "Distribution estimate", "Not reported ")))|> 
  ggplot() +
  geom_histogram(aes(x=What.is.the.size.of.the.calibration.output.V2, fill=Nature.of.calibration.results))+
  scale_x_log10(breaks= c(1, 10, 100, 1000, 10000, 100000, 500000)) + 
  theme_bw()+
  facet_grid(Aim.of.calibration.procedure ~ ., scales = "free",labeller=label_wrap_gen(width=.1))+
  xlab("Size of calibration output")+
  labs(fill = "Nature of calibration results")

```



# Association between disease and algorithm AIM
```{r}
library(cartography)
                                                                    
# chordDiagram
# install.packages("circlize")
library(circlize)
clean_data |> 
  separate_rows(Disease.type..choose.all.that.apply., sep = "; ")|> 
  select(Aim.of.calibration.procedure,  Disease.type..choose.all.that.apply.)|>
  chordDiagram(grid.col = carto.pal(pal1 = "pastel.pal" ,n1 = 6))

# Barplot - Proportion stacked
clean_data|> 
  separate_rows(Disease.type..choose.all.that.apply., sep = "; ")|>
  group_by(Aim.of.calibration.procedure, Disease.type..choose.all.that.apply.) |>
  summarise(Count = n(), .groups = 'drop') |>
  group_by(Disease.type..choose.all.that.apply.) |>
  mutate(Proportion = Count / sum(Count)) |>
  ggplot(aes(x=Disease.type..choose.all.that.apply., y = Proportion, fill = Aim.of.calibration.procedure)) +
  geom_bar(stat = "identity", position = "fill") +
  theme_classic() +
  xlab("Aim of calibration algorithm") +
  ylab("Proportion") +
  labs(fill = "Aim of calibration algorithm") +
  scale_fill_manual(values = carto.pal(pal1 = "pastel.pal" ,n1 = 5))

```
# Association between disease and algorithm FAMILY
```{r}
# Barplot - count
clean_data |> 
    separate_rows(Calibration.algorithm.Family, sep = "; ")|> 
    separate_rows(Disease.type..choose.all.that.apply., sep = "; ") |>
  mutate(
    Calibration.algorithm.Family = fct_infreq(Calibration.algorithm.Family),  
    Calibration.algorithm.Family = fct_relevel(Calibration.algorithm.Family, 
                                               c("Other ", "Not reported"), after = Inf))  |> 
  ggplot(aes(x=Calibration.algorithm.Family, fill = Aim.of.calibration.procedure))+
  geom_bar() +
     facet_grid(Disease.type..choose.all.that.apply.~.)+
     theme_classic() +
     xlab("Calibration algorithm family") +
     ylab("Count") +
     labs(fill = "Aim of calibration algorithm") +
     theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  scale_fill_manual(values = carto.pal(pal1 = "pastel.pal" ,n1 = 5))
```

