---
title: "Objective 1 - Summaries"
output: html_document
date: "2024-05-08"
Author: Léa Cavalli
---

# Set up environment
```{r}
# Clean environment
rm( list = ls() )

# load necessary libraries
library(tidyverse)

# Load data
setwd("~/GitHub/Calibration-Review/1.Data Cleaning")
clean_data <- read.csv("Clean_data.csv")
```


# 0. General 
```{r}
# 0.1 Year published 
df_0.1 <- clean_data |> 
  group_by(Year.published) |>
  summarise(Count=n(), 
            Percentage= 100*round(Count/nrow(clean_data), 3))|> 
  rename("Options" ="Year.published")|> 
  mutate(Field= "0.1 Year published", .before = Options)


# 0.2 Disease type 
df_0.2 <- clean_data |>
  select(Disease.type..choose.all.that.apply.)|> 
  separate_rows(Disease.type..choose.all.that.apply., sep = "; ")|> 
  group_by(Disease.type..choose.all.that.apply.) |>
  summarise(Count=n()) |>
  mutate(Percentage= 100*round(Count/nrow(clean_data), 3))|> 
  rename("Options" ="Disease.type..choose.all.that.apply.")|> 
  mutate(Field= "0.2 Disease type", .before = Options)

# clean_data |>
#   filter(grepl(";",Disease.type..choose.all.that.apply.))|>
#   group_by(Disease.type..choose.all.that.apply.)|>
#   summarise(Count=n()) |>
#   mutate(Percentage= 100*round(Count/nrow(clean_data), 3))


# 0.3 Model type 
df_0.3 <- clean_data |> 
    mutate(Model.type = factor(Model.type, levels= c("Compartmental", "Individual-based", "Hawkes Process", "Not reported", "Other")))|>
  group_by(Model.type) |>
  summarise(Count=n(), 
            Percentage= 100*round(Count/nrow(clean_data), 3))|> 
  rename("Options" ="Model.type")|> 
  mutate(Field= "0.3 Model type", .before = Options)


# 0.4 Stochasticity in model 
df_0.4 <- clean_data |> 
  mutate(Stochasticity.in.model = factor(Stochasticity.in.model, levels= c("Deterministic model ", "Stochastic model", "Not reported")))|> 
  group_by(Stochasticity.in.model) |>
  summarise(Count=n(), 
            Percentage= 100*round(Count/nrow(clean_data), 3))|> 
  rename("Options" ="Stochasticity.in.model")|> 
  mutate(Field= "0.4 Stochasticity in model", .before = Options)

```

# A. Purpose
```{r}
# A.1 Scientific problem being solved (what is the purpose of calibration?) 
df_A.1 <- clean_data |>
  select(Scientific.problem.being.solved)|> 
  separate_rows(Scientific.problem.being.solved, sep = "; ")|> 
  group_by(Scientific.problem.being.solved) |>
  summarise(Count=n()) |>
  mutate(Percentage= 100*round(Count/nrow(clean_data), 3))|> 
  rename("Options" ="Scientific.problem.being.solved")|> 
  mutate(Field= "A.1 Scientific problem being solved (what is the purpose of calibration?)", .before = Options)


```

# B. Inputs 
# B.1. Parameter inputs
```{r}
# B.1.1. Beliefs or evidence
df_B.1.1 <- clean_data |> 
  mutate(External.beliefs.or.evidence = factor(External.beliefs.or.evidence, levels= c("Prior knowledge is incorporated for at least one parameter to be calibrated; e.g., as a prior distribution over the parameter.", "No prior knowledge is incorporated for parameters to be calibrated. ", "Not reported")))|> 
  group_by(External.beliefs.or.evidence) |>
  summarise(Count=n(), 
            Percentage= 100*round(Count/nrow(clean_data), 3))|> 
  rename("Options" ="External.beliefs.or.evidence")|> 
  mutate(Field= "B.1.1. Beliefs or evidence", .before = Options)

# B.1.2. Choice of parameters to calibrate
df_B.1.2 <- clean_data |> 
  mutate(Choice.of.parameters.to.calibrate = factor(Choice.of.parameters.to.calibrate, levels= c("All parameters", "Subset of parameters", "Not reported")))|> 
  group_by(Choice.of.parameters.to.calibrate) |>
  summarise(Count=n(), 
            Percentage= 100*round(Count/nrow(clean_data), 3))|> 
  rename("Options" ="Choice.of.parameters.to.calibrate")|> 
  mutate(Field= "B.1.2. Choice of parameters to calibrate", .before = Options)


# B.1.3. What justification was provided for choice of parameters to calibrate? Only for studies which calibrated a subset of parameters.
df_B.1.3 <- clean_data |>
  select(What.justification.was.provided.for.choice.of.parameters.to.calibrate.)|> 
  group_by(What.justification.was.provided.for.choice.of.parameters.to.calibrate.) |>
  summarise(Count=n()) |>
  mutate(Percentage= 100*round(Count/nrow(clean_data), 3))|> 
  rename("Options" ="What.justification.was.provided.for.choice.of.parameters.to.calibrate.")|> 
  mutate(Field= "B.1.3. What justification was provided for choice of parameters to calibrate? Only for studies which calibrated a subset of parameters.", .before = Options)|>
  mutate(Options = factor(Options, levels=c("Parameters are relevant to question of interest.", "Parameters are uncertain.",  "Parameters are relevant to question of interest.; Parameters are uncertain.","Not reported ", "Other")))|> 
  arrange(Options)



# B.1.4. How many parameters were calibrated?
df_B.1.4 <- clean_data |> 
  mutate(How.many.parameters.were.calibrated. = factor(How.many.parameters.were.calibrated., levels= c("Single ", "Multiple", "Not reported")))|> 
  group_by(How.many.parameters.were.calibrated.) |>
  summarise(Count=n(), 
            Percentage= 100*round(Count/nrow(clean_data), 3))|> 
  rename("Options" ="How.many.parameters.were.calibrated.")|> 
  mutate(Field= "B.1.4. How many parameters were calibrated?", .before = Options)



```
# B.2. Calibration targets
```{r}
# B.2.1. Type of data used for defining calibration targets
df_B.2.1 <- clean_data  |>
  select(Type.of.data.used.for.defining.calibration.targets..select.all.that.apply.)|> 
  separate_rows(Type.of.data.used.for.defining.calibration.targets..select.all.that.apply., sep = "; ")|> 
  group_by(Type.of.data.used.for.defining.calibration.targets..select.all.that.apply.) |>
  summarise(Count=n()) |>
  mutate(Percentage= 100*round(Count/nrow(clean_data), 3))|> 
  rename("Options" ="Type.of.data.used.for.defining.calibration.targets..select.all.that.apply.")|> 
  mutate(Field= "B.2.1. Type of data used for defining calibration targets", .before = Options)
order_type <- c((df_B.2.1 |> 
  filter(! Options %in% c("Other", "Not reported "))|> 
  arrange(-Count) |> 
  pull(Options)), "Other", "Not reported ")
df_B.2.1 <- df_B.2.1|> 
  mutate(Options = factor(Options, levels=order_type))|> 
  arrange(Options)


# B.2.2. Resolution of data used for defining calibration targets
df_B.2.2 <- clean_data |>
  select(Resolution.of.data..used.for.defining.calibration.targets)|> 
  group_by(Resolution.of.data..used.for.defining.calibration.targets) |>
  summarise(Count=n()) |>
  mutate(Percentage= 100*round(Count/nrow(clean_data), 3))|> 
  rename("Options" ="Resolution.of.data..used.for.defining.calibration.targets")|> 
  mutate(Options = factor(Options, levels=c("Empirical data or statistical summaries of empirical data (e.g., WHO case notification data) ", "Modeled estimates  (e.g., WHO TB incidence estimates)",  "Empirical data or statistical summaries of empirical data (e.g., WHO case notification data) ; Modeled estimates  (e.g., WHO TB incidence estimates)","Not reported ")))|> 
  mutate(Field= "B.2.2. Resolution of data used for defining calibration targets", .before = Options)

#  B.2.3.  How many calibration targets were used for estimation?
df_B.2.3 <- clean_data |> 
  group_by(How.many.calibration.targets.were.used.for.estimation.) |>
  summarise(Count=n(), 
            Percentage= 100*round(Count/nrow(clean_data), 3))|> 
  rename("Options" ="How.many.calibration.targets.were.used.for.estimation.")|> 
  mutate(Field= "B.2.3.  How many calibration targets were used for estimation?", .before = Options)

```



# C. Process
```{r}
# C.1. Number of steps 
df_C.1 <- clean_data |> 
  group_by(Number.of.steps..single.or.sequential.) |>
  summarise(Count=n(), 
            Percentage= 100*round(Count/nrow(clean_data), 3))|> 
  rename("Options" ="Number.of.steps..single.or.sequential.")|> 
  mutate(Field= "C.1. Number of steps", .before = Options)

# C.2.1 Name of calibration algorithm 
df_C.2.1 <- clean_data |>
  select(Name.of.calibration.algorithm)|> 
  separate_rows(Name.of.calibration.algorithm, sep = "; ")|> 
  group_by(Name.of.calibration.algorithm) |>
  summarise(Count=n()) |>
  mutate(Percentage= 100*round(Count/nrow(clean_data), 3))|> 
  rename("Options" ="Name.of.calibration.algorithm")|> 
  mutate(Field= "C.2.1. Name of calibration algorithm", .before = Options)
ordered_Name.of.calibration.algorithm <- c((df_C.2.1 |>
  filter(!Options %in% c( "Not reported", "Other "))|>
  arrange(-Count)|>
  pull(Options)), "Other ", "Not reported")
df_C.2.1  <- df_C.2.1|> 
  mutate(Options = factor(Options, levels=ordered_Name.of.calibration.algorithm))|> 
  arrange(Options)

# C.2.2 calibration algorithm Family
df_C.2.2 <- clean_data |>
  select(Calibration.algorithm.Family)|> 
  separate_rows(Calibration.algorithm.Family, sep = "; ")|> 
  group_by(Calibration.algorithm.Family) |>
  summarise(Count=n()) |>
  mutate(Percentage= 100*round(Count/nrow(clean_data), 3))|> 
  rename("Options" ="Calibration.algorithm.Family")|> 
  mutate(Field= "C.2.2 calibration algorithm Family", .before = Options)
ordered_Name.of.calibration.algorithm <- c((df_C.2.2 |>
  filter(!Options %in% c( "Not reported", "Other "))|>
  arrange(-Count)|>
  pull(Options)), "Other ", "Not reported")
df_C.2.2  <- df_C.2.2|> 
  mutate(Options = factor(Options, levels=ordered_Name.of.calibration.algorithm))|> 
  arrange(Options)

# C.3. Is calibration implementation (code) available in an open-access repository? 
df_C.3 <- clean_data |> 
  group_by(Is.calibration.implementation..code..available.in.an.open.access.repository.) |>
  summarise(Count=n(), 
            Percentage= 100*round(Count/nrow(clean_data), 3))|> 
  rename("Options" ="Is.calibration.implementation..code..available.in.an.open.access.repository.")|> 
  mutate(Field= "C.3. Is calibration implementation (code) available in an open-access repository?", .before = Options)


# C.4. Goodness-of-fit (GOF) measure employed within calibration algorithm
df_C.4 <- clean_data |> 
    mutate(Goodness.of.fit..GOF..measure.employed.within.calibration.algorithm = factor(Goodness.of.fit..GOF..measure.employed.within.calibration.algorithm, levels= c("Ad-hoc distance function (as in Approximate Bayesian Computation or least squares)", "Data likelihood ", "Not reported", "Not clear", "Other ")))|> 
group_by(Goodness.of.fit..GOF..measure.employed.within.calibration.algorithm) |>
  summarise(Count=n(), 
            Percentage= 100*round(Count/nrow(clean_data), 3))|> 
  rename("Options" ="Goodness.of.fit..GOF..measure.employed.within.calibration.algorithm")|> 
  mutate(Field= "C.4. Goodness-of-fit (GOF) measure employed within calibration algorithm", .before = Options)

# C.5. What programming language was used for calibration?
df_C.5 <- clean_data |>
  select(What.programming.language.was.used.for.calibration.)|> 
  separate_rows(What.programming.language.was.used.for.calibration., sep = "; ")|> 
  group_by(What.programming.language.was.used.for.calibration.) |>
  summarise(Count=n()) |>
  mutate(Percentage= 100*round(Count/nrow(clean_data), 3))|> 
  rename("Options" ="What.programming.language.was.used.for.calibration.")|> 
  mutate(Field= "C.5. What programming language was used for calibration?", .before = Options)|> 
  mutate(Options = factor(Options, levels=c("R", "Python", "Matlab", "Julia", "C++", "Not reported", "Other ")))|>
  arrange(Options)

# clean_data |>
#   filter(grepl(";",What.programming.language.was.used.for.calibration.))|>
#   summarise(Count=n()) |>
#   mutate(Percentage= 100*round(Count/nrow(clean_data), 3))

# C.6. Do authors list any programming packages used for calibration?
df_C.6 <- clean_data |> 
  mutate(Do.authors.list.any.programming.packages.used.for.calibration. = factor(Do.authors.list.any.programming.packages.used.for.calibration., levels= c("Yes", "No")))|> 
  group_by(Do.authors.list.any.programming.packages.used.for.calibration.) |>
  summarise(Count=n(), 
            Percentage= 100*round(Count/nrow(clean_data), 3))|> 
  rename("Options" ="Do.authors.list.any.programming.packages.used.for.calibration.")|> 
  mutate(Field= "C.6. Do authors list any programming packages used for calibration?", .before = Options)

```


# D. Output 
```{r}
# D.1. Nature of calibration results
composite <- clean_data |> 
  filter(grepl(";", Nature.of.calibration.results))|> 
  select(Covidence.ID, Nature.of.calibration.results,What.is.the.size.of.the.calibration.output.)
composite$Nature <- sapply(strsplit(composite$Nature.of.calibration.results, "; "), function(x) trimws(tail(x, 1)))
df_D.1 <- clean_data |> 
  mutate(Nature.of.calibration.results= ifelse(Covidence.ID %in% composite$Covidence.ID, composite$Nature, Nature.of.calibration.results))|> 
  mutate(Nature.of.calibration.results= ifelse(Nature.of.calibration.results =="Not reported", "Not reported ", Nature.of.calibration.results))|> 
    mutate(Nature.of.calibration.results = factor(Nature.of.calibration.results, levels= c("Point estimate (single parameter / parameter set)", "Sample estimate (multiple parameter sets)", "Distribution estimate (a distribution function which generates parameter values)", "Not reported ", "Other ")))|> 
  group_by(Nature.of.calibration.results) |>
  summarise(Count=n(), 
            Percentage= 100*round(Count/nrow(clean_data), 3))|> 
  rename("Options" ="Nature.of.calibration.results")|> 
  mutate(Field= "D.1. Nature of calibration results", .before = Options)

# D.2. How are calibration results reported?
df_D.2 <- clean_data |>
  select(How.are.calibration.results.reported.)|> 
  group_by(How.are.calibration.results.reported.) |>
  summarise(Count=n()) |>
  mutate(Percentage= 100*round(Count/nrow(clean_data), 3))|> 
  rename("Options" ="How.are.calibration.results.reported.")|> 
  mutate(Field= "D.2. How are calibration results reported?", .before = Options)|> 
  mutate(Options = factor(Options, levels=c("Numerical: e.g. as value(s).", "Graphical: e.g., as a plot of calibrated model trend versus calibration targets. ", "Numerical: e.g. as value(s).; Graphical: e.g., as a plot of calibrated model trend versus calibration targets. ","Calibration results are not reported. ")))|> 
  arrange(Options)


# D.3. How is uncertainty in calibration outputs reported? 
df_D.3 <- clean_data |>
  select(How.is.uncertainty.in.calibration.outputs.reported.)|> 
  group_by(How.is.uncertainty.in.calibration.outputs.reported.) |>
  summarise(Count=n()) |>
  mutate(Percentage= 100*round(Count/nrow(clean_data), 3))|> 
  rename("Options" ="How.is.uncertainty.in.calibration.outputs.reported.")|> 
  mutate(Field= "D.3. How is uncertainty in calibration outputs reported?", .before = Options)|> 
  mutate(Options = factor(Options, levels=c("Numerical: As uncertainty intervals around estimates or model outputs. e.g., 95% CI: 1.5 - 4.5.", "Graphical: As a plot. E.g., a line with shaded areas indicating uncertainty intervals ", "Numerical: As uncertainty intervals around estimates or model outputs. e.g., 95% CI: 1.5 - 4.5.; Graphical: As a plot. E.g., a line with shaded areas indicating uncertainty intervals ", "Uncertainty in calibration outputs is not reported.")))|> 
  arrange(Options)

# D.4. What is the size of the calibration output? 
df_D.4 <- clean_data |> 
  mutate(size.of.the.calibration.output.reported = ifelse(What.is.the.size.of.the.calibration.output. == "Not reported", "Not reported", "[Number provided]"))|> 
  mutate(size.of.the.calibration.output.reported = factor(size.of.the.calibration.output.reported, levels= c("[Number provided]", "Not reported")))|> 
  group_by(size.of.the.calibration.output.reported) |>
  summarise(Count=n(), 
            Percentage= 100*round(Count/nrow(clean_data), 3))|> 
  rename("Options" ="size.of.the.calibration.output.reported")|> 
  mutate(Field= "D.4. What is the size of the calibration output?", .before = Options)
```


# Assemble final dataframe
```{r}
Objective1_df <- rbind(df_0.1, df_0.2, df_0.3, df_0.4, 
                       df_A.1,
                       df_B.1.1, df_B.1.2, df_B.1.3, df_B.1.4,
                       df_B.2.1, df_B.2.2, df_B.2.3, 
                       df_C.1, df_C.2.1, df_C.2.2, df_C.3, df_C.4, df_C.5, df_C.6, 
                       df_D.1, df_D.2, df_D.3, df_D.4)

Objective1_df
```

# Write a file
```{r}
library(xlsx)
setwd("~/GitHub/Calibration-Review/3.Results/Tables")
write.xlsx(as.data.frame(Objective1_df), file="Sheet S2.xlsx",
  sheetName = "Table 2", append=TRUE , row.names = F, col.names = T)
```





